<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LunaPacketSniffer.Core\LunaPacketSniffer.Core.csproj" />
    <ProjectReference Include="..\LunaPacketSniffer.Networking\LunaPacketSniffer.Networking.csproj" />
    <ProjectReference Include="..\LunaPacketSniffer.Protocols\LunaPacketSniffer.Protocols.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>
</Project>
