name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Ninja
        run: choco install ninja -y

      - name: Configure CMake
        run: cmake --preset windows-x64 -G "Visual Studio 18 2026"

      - name: Build C++
        run: cmake --build --preset windows-x64-debug --config Release

      - name: Build C#
        run: dotnet build LunaPacketSniffer.sln --configuration Release

      - name: Run tests
        run: dotnet test LunaPacketSniffer.sln --configuration Release --no-build

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: LunaPacketSniffer-windows
          path: LunaPacketSniffer.App\bin
